spring.application.name=mtgcm-api
spring.output.ansi.enabled=ALWAYS

# Datasource settings
spring.datasource.url=jdbc:h2:file:./mtgcm-db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.h2.console.enabled=true

logging.level.root=info

origin.url=http://localhost:5173

# Scryfall settings
scryfall.base-url=https://api.scryfall.com
scryfall.user-agent-header=mtgcm-api/1.0
scryfall.accept-header=application/json;q=0.9,*/*;q=0.8
scryfall.sets-uri=/sets
scryfall.set-by-code-uri=/sets/%s
scryfall.set-cards-uri=https://api.scryfall.com/cards/search?include_extras=true&include_variations=true&order=set&q=e:%s&unique=prints

# Cardmarket settings
cardmarket.base-url=https://apiv2.cardmarket.com/ws/v2.0
cardmarket.app-token=${CARDMARKET_APP_TOKEN}
cardmarket.app-secret=${CARDMARKET_APP_SECRET}
cardmarket.access-token=${CARDMARKET_ACCESS_TOKEN}
cardmarket.access-token-secret=${CARDMARKET_ACCESS_TOKEN_SECRET}
cardmarket.wantslist-uri=/wantslist