spring.application.name=mtgcm-api
spring.output.ansi.enabled=ALWAYS

# Datasource settings
spring.datasource.url=jdbc:h2:file:./mtgcm-db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.h2.console.enabled=true

logging.level.root=info

origin.url=http://localhost:5173

# Scryfall settings
base-url=https://api.scryfall.com
max-in-mem-size=-1
user-agent-header=mtgcm-api/1.0
accept-header=application/json;q=0.9,*/*;q=0.8
sets-uri=/sets
set-by-code-uri=/sets/%s
set-cards-uri=https://api.scryfall.com/cards/search?include_extras=true&include_variations=true&order=set&q=e:%s&unique=prints