export interface CardSet {
  id: string;
  name: string;
  type: string;
  releaseDate: string;
  totalCards: number;
  collectedCards: number;
  iconUri?: string;
}

export interface Card {
  id: string;
  sortNumber: number;
  name: string;
  type: string;
  rarity: "Common" | "Uncommon" | "Rare" | "Mythic Rare";
  manaCost: string;
  price: number;
  collected: boolean;
  imageUri?: string;
  oracleText?: string;
  artist?: string;
  power?: string;
  toughness?: string;
  setName?: string;
  setCode?: string;
}

// TODO: mantenemos de momento hasta que enganchemos al backend
export const mockSets: CardSet[] = [
  {
    id: "dom",
    name: "Dominaria",
    type: "Expansion",
    releaseDate: "2018-04-27",
    totalCards: 269,
    collectedCards: 187,
  },
  {
    id: "rna",
    name: "Ravnica Allegiance",
    type: "Expansion",
    releaseDate: "2019-01-25",
    totalCards: 259,
    collectedCards: 142,
  },
  {
    id: "war",
    name: "War of the Spark",
    type: "Expansion",
    releaseDate: "2019-05-03",
    totalCards: 264,
    collectedCards: 264,
  },
  {
    id: "m20",
    name: "Core Set 2020",
    type: "Core Set",
    releaseDate: "2019-07-12",
    totalCards: 280,
    collectedCards: 98,
  },
  {
    id: "eld",
    name: "Throne of Eldraine",
    type: "Expansion",
    releaseDate: "2019-10-04",
    totalCards: 269,
    collectedCards: 45,
  },
  {
    id: "thb",
    name: "Theros Beyond Death",
    type: "Expansion",
    releaseDate: "2020-01-24",
    totalCards: 254,
    collectedCards: 210,
  },
  {
    id: "iko",
    name: "Ikoria: Lair of Behemoths",
    type: "Expansion",
    releaseDate: "2020-04-17",
    totalCards: 274,
    collectedCards: 0,
  },
  {
    id: "znr",
    name: "Zendikar Rising",
    type: "Expansion",
    releaseDate: "2020-09-25",
    totalCards: 280,
    collectedCards: 156,
  },
];

// TODO: mantenemos de momento hasta que enganchemos al backend
export const mockCards: Record<string, Card[]> = {
  dom: [
    {
      id: "dom-001",
      sortNumber: 1,
      name: "Karn, Scion of Urza",
      type: "Legendary Planeswalker",
      rarity: "Mythic Rare",
      manaCost: "{4}",
      price: 12.5,
      collected: true,
    },
    {
      id: "dom-002",
      sortNumber: 2,
      name: "Teferi, Hero of Dominaria",
      type: "Legendary Planeswalker",
      rarity: "Mythic Rare",
      manaCost: "{3}{W}{U}",
      price: 28.0,
      collected: true,
    },
    {
      id: "dom-003",
      sortNumber: 3,
      name: "History of Benalia",
      type: "Enchantment Saga",
      rarity: "Mythic Rare",
      manaCost: "{1}{W}{W}",
      price: 3.5,
      collected: false,
    },
    {
      id: "dom-004",
      sortNumber: 4,
      name: "Lyra Dawnbringer",
      type: "Legendary Creature",
      rarity: "Mythic Rare",
      manaCost: "{3}{W}{W}",
      price: 8.0,
      collected: true,
    },
    {
      id: "dom-005",
      sortNumber: 5,
      name: "Shalai, Voice of Plenty",
      type: "Legendary Creature",
      rarity: "Rare",
      manaCost: "{3}{W}",
      price: 4.25,
      collected: true,
    },
    {
      id: "dom-006",
      sortNumber: 6,
      name: "Seal Away",
      type: "Enchantment",
      rarity: "Uncommon",
      manaCost: "{1}{W}",
      price: 0.75,
      collected: true,
    },
    {
      id: "dom-007",
      sortNumber: 7,
      name: "Knight of Grace",
      type: "Creature",
      rarity: "Uncommon",
      manaCost: "{1}{W}",
      price: 0.5,
      collected: false,
    },
    {
      id: "dom-008",
      sortNumber: 8,
      name: "Dauntless Bodyguard",
      type: "Creature",
      rarity: "Uncommon",
      manaCost: "{W}",
      price: 0.35,
      collected: true,
    },
    {
      id: "dom-009",
      sortNumber: 9,
      name: "Benalish Marshal",
      type: "Creature",
      rarity: "Rare",
      manaCost: "{W}{W}{W}",
      price: 2.0,
      collected: true,
    },
    {
      id: "dom-010",
      sortNumber: 10,
      name: "Invoke the Divine",
      type: "Instant",
      rarity: "Common",
      manaCost: "{2}{W}",
      price: 0.1,
      collected: true,
    },
    {
      id: "dom-011",
      sortNumber: 11,
      name: "Adamant Will",
      type: "Instant",
      rarity: "Common",
      manaCost: "{1}{W}",
      price: 0.05,
      collected: false,
    },
    {
      id: "dom-012",
      sortNumber: 12,
      name: "Blessed Light",
      type: "Instant",
      rarity: "Common",
      manaCost: "{4}{W}",
      price: 0.05,
      collected: true,
    },
  ],
  rna: [
    {
      id: "rna-001",
      sortNumber: 1,
      name: "Angel of Grace",
      type: "Creature",
      rarity: "Mythic Rare",
      manaCost: "{3}{W}{W}",
      price: 2.5,
      collected: true,
    },
    {
      id: "rna-002",
      sortNumber: 2,
      name: "Domri, Chaos Bringer",
      type: "Legendary Planeswalker",
      rarity: "Mythic Rare",
      manaCost: "{2}{R}{G}",
      price: 4.0,
      collected: false,
    },
    {
      id: "rna-003",
      sortNumber: 3,
      name: "Hydroid Krasis",
      type: "Creature",
      rarity: "Mythic Rare",
      manaCost: "{X}{G}{U}",
      price: 18.0,
      collected: true,
    },
    {
      id: "rna-004",
      sortNumber: 4,
      name: "Kaya, Orzhov Usurper",
      type: "Legendary Planeswalker",
      rarity: "Mythic Rare",
      manaCost: "{1}{W}{B}",
      price: 3.5,
      collected: false,
    },
    {
      id: "rna-005",
      sortNumber: 5,
      name: "Prime Speaker Vannifar",
      type: "Legendary Creature",
      rarity: "Mythic Rare",
      manaCost: "{2}{G}{U}",
      price: 5.0,
      collected: true,
    },
    {
      id: "rna-006",
      sortNumber: 6,
      name: "Spawn of Mayhem",
      type: "Creature",
      rarity: "Mythic Rare",
      manaCost: "{2}{B}{B}",
      price: 3.0,
      collected: true,
    },
    {
      id: "rna-007",
      sortNumber: 7,
      name: "Deputy of Detention",
      type: "Creature",
      rarity: "Rare",
      manaCost: "{1}{W}{U}",
      price: 1.5,
      collected: false,
    },
    {
      id: "rna-008",
      sortNumber: 8,
      name: "Growth-Chamber Guardian",
      type: "Creature",
      rarity: "Rare",
      manaCost: "{1}{G}",
      price: 1.0,
      collected: true,
    },
  ],
  war: [
    {
      id: "war-001",
      sortNumber: 1,
      name: "Nicol Bolas, Dragon-God",
      type: "Legendary Planeswalker",
      rarity: "Mythic Rare",
      manaCost: "{U}{B}{B}{B}{R}",
      price: 15.0,
      collected: true,
    },
    {
      id: "war-002",
      sortNumber: 2,
      name: "Liliana, Dreadhorde General",
      type: "Legendary Planeswalker",
      rarity: "Mythic Rare",
      manaCost: "{4}{B}{B}",
      price: 22.0,
      collected: true,
    },
    {
      id: "war-003",
      sortNumber: 3,
      name: "Gideon Blackblade",
      type: "Legendary Planeswalker",
      rarity: "Mythic Rare",
      manaCost: "{1}{W}{W}",
      price: 8.0,
      collected: true,
    },
    {
      id: "war-004",
      sortNumber: 4,
      name: "Nissa, Who Shakes the World",
      type: "Legendary Planeswalker",
      rarity: "Rare",
      manaCost: "{3}{G}{G}",
      price: 6.5,
      collected: true,
    },
    {
      id: "war-005",
      sortNumber: 5,
      name: "Teferi, Time Raveler",
      type: "Legendary Planeswalker",
      rarity: "Rare",
      manaCost: "{1}{W}{U}",
      price: 12.0,
      collected: true,
    },
    {
      id: "war-006",
      sortNumber: 6,
      name: "Narset, Parter of Veils",
      type: "Legendary Planeswalker",
      rarity: "Uncommon",
      manaCost: "{1}{U}{U}",
      price: 2.0,
      collected: true,
    },
  ],
  m20: [
    {
      id: "m20-001",
      sortNumber: 1,
      name: "Chandra, Awakened Inferno",
      type: "Legendary Planeswalker",
      rarity: "Mythic Rare",
      manaCost: "{4}{R}{R}",
      price: 10.0,
      collected: true,
    },
    {
      id: "m20-002",
      sortNumber: 2,
      name: "Sorin, Imperious Bloodlord",
      type: "Legendary Planeswalker",
      rarity: "Mythic Rare",
      manaCost: "{2}{B}",
      price: 8.5,
      collected: false,
    },
    {
      id: "m20-003",
      sortNumber: 3,
      name: "Cavalier of Thorns",
      type: "Creature",
      rarity: "Mythic Rare",
      manaCost: "{2}{G}{G}{G}",
      price: 5.0,
      collected: true,
    },
    {
      id: "m20-004",
      sortNumber: 4,
      name: "Field of the Dead",
      type: "Land",
      rarity: "Rare",
      manaCost: "",
      price: 15.0,
      collected: false,
    },
    {
      id: "m20-005",
      sortNumber: 5,
      name: "Veil of Summer",
      type: "Instant",
      rarity: "Uncommon",
      manaCost: "{G}",
      price: 4.0,
      collected: true,
    },
  ],
  eld: [
    {
      id: "eld-001",
      sortNumber: 1,
      name: "Oko, Thief of Crowns",
      type: "Legendary Planeswalker",
      rarity: "Mythic Rare",
      manaCost: "{1}{G}{U}",
      price: 35.0,
      collected: false,
    },
    {
      id: "eld-002",
      sortNumber: 2,
      name: "The Great Henge",
      type: "Legendary Artifact",
      rarity: "Mythic Rare",
      manaCost: "{7}{G}{G}",
      price: 45.0,
      collected: true,
    },
    {
      id: "eld-003",
      sortNumber: 3,
      name: "Embercleave",
      type: "Legendary Artifact",
      rarity: "Mythic Rare",
      manaCost: "{4}{R}{R}",
      price: 12.0,
      collected: false,
    },
    {
      id: "eld-004",
      sortNumber: 4,
      name: "Brazen Borrower",
      type: "Creature",
      rarity: "Mythic Rare",
      manaCost: "{1}{U}{U}",
      price: 8.0,
      collected: false,
    },
    {
      id: "eld-005",
      sortNumber: 5,
      name: "Murderous Rider",
      type: "Creature",
      rarity: "Rare",
      manaCost: "{1}{B}{B}",
      price: 3.0,
      collected: true,
    },
  ],
  thb: [
    {
      id: "thb-001",
      sortNumber: 1,
      name: "Heliod, Sun-Crowned",
      type: "Legendary Creature",
      rarity: "Mythic Rare",
      manaCost: "{2}{W}",
      price: 14.0,
      collected: true,
    },
    {
      id: "thb-002",
      sortNumber: 2,
      name: "Thassa, Deep-Dwelling",
      type: "Legendary Creature",
      rarity: "Mythic Rare",
      manaCost: "{3}{U}",
      price: 6.0,
      collected: true,
    },
    {
      id: "thb-003",
      sortNumber: 3,
      name: "Erebos, Bleak-Hearted",
      type: "Legendary Creature",
      rarity: "Mythic Rare",
      manaCost: "{3}{B}",
      price: 4.0,
      collected: true,
    },
    {
      id: "thb-004",
      sortNumber: 4,
      name: "Purphoros, Bronze-Blooded",
      type: "Legendary Creature",
      rarity: "Mythic Rare",
      manaCost: "{4}{R}",
      price: 3.5,
      collected: false,
    },
    {
      id: "thb-005",
      sortNumber: 5,
      name: "Nylea, Keen-Eyed",
      type: "Legendary Creature",
      rarity: "Mythic Rare",
      manaCost: "{3}{G}",
      price: 3.0,
      collected: true,
    },
    {
      id: "thb-006",
      sortNumber: 6,
      name: "Kroxa, Titan of Death's Hunger",
      type: "Legendary Creature",
      rarity: "Mythic Rare",
      manaCost: "{B}{R}",
      price: 18.0,
      collected: true,
    },
  ],
  iko: [
    {
      id: "iko-001",
      sortNumber: 1,
      name: "Lukka, Coppercoat Outcast",
      type: "Legendary Planeswalker",
      rarity: "Mythic Rare",
      manaCost: "{3}{R}{R}",
      price: 2.0,
      collected: false,
    },
    {
      id: "iko-002",
      sortNumber: 2,
      name: "Vivien, Monsters' Advocate",
      type: "Legendary Planeswalker",
      rarity: "Mythic Rare",
      manaCost: "{3}{G}{G}",
      price: 5.0,
      collected: false,
    },
    {
      id: "iko-003",
      sortNumber: 3,
      name: "Lurrus of the Dream-Den",
      type: "Legendary Creature",
      rarity: "Rare",
      manaCost: "{1}{W/B}{W/B}",
      price: 6.0,
      collected: false,
    },
    {
      id: "iko-004",
      sortNumber: 4,
      name: "Fiend Artisan",
      type: "Creature",
      rarity: "Mythic Rare",
      manaCost: "{B/G}{B/G}",
      price: 4.5,
      collected: false,
    },
    {
      id: "iko-005",
      sortNumber: 5,
      name: "Shark Typhoon",
      type: "Enchantment",
      rarity: "Rare",
      manaCost: "{5}{U}",
      price: 8.0,
      collected: false,
    },
  ],
  znr: [
    {
      id: "znr-001",
      sortNumber: 1,
      name: "Omnath, Locus of Creation",
      type: "Legendary Creature",
      rarity: "Mythic Rare",
      manaCost: "{R}{G}{W}{U}",
      price: 12.0,
      collected: true,
    },
    {
      id: "znr-002",
      sortNumber: 2,
      name: "Nahiri, Heir of the Ancients",
      type: "Legendary Planeswalker",
      rarity: "Mythic Rare",
      manaCost: "{2}{R}{W}",
      price: 3.0,
      collected: false,
    },
    {
      id: "znr-003",
      sortNumber: 3,
      name: "Jace, Mirror Mage",
      type: "Legendary Planeswalker",
      rarity: "Mythic Rare",
      manaCost: "{1}{U}{U}",
      price: 2.5,
      collected: true,
    },
    {
      id: "znr-004",
      sortNumber: 4,
      name: "Agadeem's Awakening",
      type: "Sorcery // Land",
      rarity: "Mythic Rare",
      manaCost: "{X}{B}{B}{B}",
      price: 18.0,
      collected: true,
    },
    {
      id: "znr-005",
      sortNumber: 5,
      name: "Sea Gate Stormcaller",
      type: "Creature",
      rarity: "Mythic Rare",
      manaCost: "{1}{U}",
      price: 2.0,
      collected: false,
    },
    {
      id: "znr-006",
      sortNumber: 6,
      name: "Scourge of the Skyclaves",
      type: "Creature",
      rarity: "Mythic Rare",
      manaCost: "{1}{B}",
      price: 4.0,
      collected: true,
    },
  ],
};
