# Console display
spring.output.ansi.enabled = ALWAYS

# Logging settings
logging.level.root = info

# Disable open in view default behaviour
spring.jpa.open-in-view = false

# Database settings
spring.datasource.url = jdbc:h2:file:./database/mtg-collection-manager
spring.datasource.driverClassName = org.h2.Driver
spring.datasource.username = sa
spring.datasource.password = root
spring.jpa.database-platform = org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto = update